### ISSUE TITLE
Error: Could not find artifacts for EtherToken from any sources

### ISSUE THREAD

**Issue by etsangsplk** [gnosis/dx-contracts#52]
I alerady have 

./node_modules/@gnosis.pm/util-contracts/

yarn test
```yarn run v1.7.0
$ truffle test
Keccak bindings are not compiled. Pure JS implementation will be used.
Using gas limit: 6500000
Using gas price: 5000000000
Optimizer enabled: true
Using default mnemonic: true
Using network 'development'.

Error: Could not find artifacts for EtherToken from any sources
    at Resolver.require (/Users/user1/dev/src/github.com/gnosis/dx-contracts/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:37:1)
    at TestResolver.require (/Users/user1/dev/src/github.com/gnosis/dx-contracts/node_modules/truffle/build/webpack:/~/truffle-core/lib/testing/testresolver.js:17:1)
    at Object.require (/Users/user1/dev/src/github.com/gnosis/dx-contracts/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:234:1)
    at ResolverIntercept.require (/Users/user1/dev/src/github.com/gnosis/dx-contracts/node_modules/truffle/build/webpack:/~/truffle-migrate/resolverintercept.js:20:1)
    at migrate (/Users/user1/dev/src/github.com/gnosis/dx-contracts/node_modules/@gnosis.pm/util-contracts/src/migrations/3_deploy_WETH.js:3:32)
    at deployer.then.then (/Users/user1/dev/src/github.com/gnosis/dx-contracts/migrations/2_DEV_migrate_dependencies.js:25:19)
    at /Users/user1/dev/src/github.com/gnosis/dx-contracts/node_modules/truffle/build/webpack:/~/truffle-deployer/src/deferredchain.js:20:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by josojo** [comment]
Hi @etsangsplk 

Thanks for reporting this issue. It is indeed an issue, but we have already a fix in the develop branch. I suggest using the tagged [npm version 0.13.1](https://www.npmjs.com/package/@gnosis.pm/dx-contracts), which fixes this issue as well. 0.13.1 works for sure.

**Comment by etsangsplk** [comment]
@josojo any plane to merge to master?

**Comment by josojo** [comment]
Now, everything was merged to master
